python modelbuilder.py Norway-base
python modelbuilder.py Norway-hp
python modelbuilder.py Norway-stes
python modelbuilder.py Germany-base
python modelbuilder.py Germany-hp
python modelbuilder.py Germany-stes
python modelbuilder.py Spain-base
python modelbuilder.py Spain-hp
python modelbuilder.py Spain-stes
